_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 16
checkpoint_interval:
    value: 3
class_names:
    value: null
cls_loss_coef:
    value: 1
dataset_dir:
    value: /ai/bennwittRepos/CloverCatcher/datasets/cloverDataSetcoco
dataset_file:
    value: roboflow
drop_path:
    value: 0
early_stopping:
    value: false
early_stopping_min_delta:
    value: 0.001
early_stopping_patience:
    value: 10
early_stopping_use_ema:
    value: false
ema_decay:
    value: 0.993
ema_tau:
    value: 100
epochs:
    value: 15
expanded_scales:
    value: true
grad_accum_steps:
    value: 1
group_detr:
    value: 13
ia_bce_loss:
    value: true
lr:
    value: 0.0001
lr_component_decay:
    value: 0.7
lr_drop:
    value: 100
lr_encoder:
    value: 0.00015
lr_vit_layer_decay:
    value: 0.8
multi_scale:
    value: true
num_select:
    value: 300
num_workers:
    value: 2
output_dir:
    value: /ai/bennwittRepos/CloverCatcher/dataPuddle/trainingArtifacts/CloverCatcher_20250429-113902
project:
    value: LuckDetector
run:
    value: CloverCatcher_20250429-113902
square_resize_div_64:
    value: true
tensorboard:
    value: true
use_ema:
    value: true
wandb:
    value: true
warmup_epochs:
    value: 0
weight_decay:
    value: 0.0001
